name: test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  bats:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Run tests
        run: ./test/bats/bin/bats test/
